Change pipelines

diff --git a/.github/workflows/pre-merge.yml b/.github/workflows/pre-merge.yml
--- a/.github/workflows/pre-merge.yml
+++ b/.github/workflows/pre-merge.yml
@@ -14,27 +14,32 @@ jobs:
     steps:
       - name: Checkout Repo
         uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
-      - name: Run tests
+      - name: Setup Gradle
         uses: gradle/gradle-build-action@v2
+      - name: Run tests
+        run: ./gradlew test
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
         with:
-          arguments: test
+          report_paths: '**/build/test-results/test/TEST-*.xml'
   publish:
     name: Check that the publish plugin works
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repo
         uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
-      - name: Check that the publish plugin works
+      - name: Setup Gradle
         uses: gradle/gradle-build-action@v2
-        with:
-          arguments: publishToMavenLocal
+      - name: Check that the publish plugin works
+        run: ./gradlew publishToMavenLocal
   staticAnalysis:
     name: Run static analysis
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repo
         uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
-      - name: Run status analysis
+      - name: Setup Gradle
         uses: gradle/gradle-build-action@v2
-        with:
-          arguments: spotlessCheck
+      - name: Run static analysis
+        run: ./gradlew spotlessCheck
